

CREATE TABLE UTENTE(
    CODIGO NUMBER PRIMARY KEY, 
	NOME VARCHAR(20), 
	SOBRENOME VARCHAR(20), 
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
	SENHA VARCHAR(10) NOT NULL, 
	DATA_NASCIMENTO DATE, 
	CATEGORIA VARCHAR(12) CHECK (categoria IN ('Aluno', 'Funcionario', 'Docente')),
	N_IDENTIFICACAO VARCHAR(15) UNIQUE, 
	TIPO_UTENTE VARCHAR(15) CHECK (tipo_utente IN ('Passageiro', 'Condutor')),
	SALDO NUMBER(9,2), 
	ESTADO VARCHAR(5) CHECK (estado IN ('On', 'Off'))
);

CREATE TABLE LOCCAL(
    CODIGO NUMBER PRIMARY KEY, 
	NOME VARCHAR2(100) NOT NULL UNIQUE, 
	LATITUDE NUMBER(6,3) UNIQUE,
	LONGITUDE NUMBER(6,3) UNIQUE
);

CREATE TABLE ALUNO(
    CODIGO NUMBER PRIMARY KEY, 
	CURSO VARCHAR(30), 
	CONSTRAINT FK_ALUNO_UTENTE FOREIGN KEY (CODIGO) REFERENCES UTENTE(CODIGO)
);

CREATE TABLE TRANSACAO(
    CODIGO NUMBER PRIMARY KEY,
	VALOR NUMBER(9,2), 
	DATA_TRANSACAO DATE, 
	CODIGO_UTENTE NUMBER, 
	PRIMARY KEY (CODIGO), 
    CONSTRAINT FK_TRANSACAO_UTENTE FOREIGN KEY (CODIGO_UTENTE) REFERENCES UTENTE (CODIGO)
);

CREATE TABLE VIATURA(
    CODIGO NUMBER PRIMARY KEY, 
	MATRICULA VARCHAR(15) UNIQUE NOT NULL, 
	MARCA VARCHAR(50), 
	MODELO VARCHAR(20), 
	LOTACAO NUMBER, 
	CODIGO_DONO NUMBER,
    CONSTRAINT FK_AUTOMOVEL_UTENTE FOREIGN KEY (CODIGO_DONO) REFERENCES UTENTE (CODIGO)
);

CREATE TABLE BOLEIA(
    CODIGO NUMBER PRIMARY KEY, 
	QTD_PASSAGEIRO NUMBER, 
	CUSTO_BOLEIA NUMBER(9,2), 
	DATA_BOLEIA DATE, 
	TIPO_BOLEIA VARCHAR(15) CHECK (tipo_boleia IN ('Unica', 'Frequente')), 
	LOCAL_ORIGEM NUMBER, 
	LOCAL_DESTINO NUMBER, 
	ESTADO VARCHAR(15) CHECK (estado IN ('Pendente', 'Confirmada', 'Concluida', 'Concelada')), 
	CODIGO_UTENTE NUMBER NOT NULL,
	CONSTRAINT FK_LOCAL_ORIGEM FOREIGN KEY (LOCAL_ORIGEM) REFERENCES LOCCAL (CODIGO), 
    CONSTRAINT FK_LOCAL_DESTINO FOREIGN KEY (LOCAL_DESTINO) REFERENCES LOCCAL (CODIGO),
    CONSTRAINT FK_COD_UTENTE FOREIGN KEY (CODIGO_UTENTE) REFERENCES UTENTE (CODIGO)
);

CREATE TABLE BOLEIA_FREQUENTE(
    CODIGO NUMBER, 
	TIPO_FREQUENCIA VARCHAR(15) CHECK (tipo_frequencia IN ('Diaria', 'Semanal', 'Mensal')), 
	DATA_TERMINO DATE, 
	CONSTRAINT FK_BOLEIA_FREQUENTE FOREIGN KEY (CODIGO) REFERENCES BOLEIA (CODIGO)
);

CREATE TABLE DIAS(
    CODIGO_BOLEIA NUMBER PRIMARY KEY NOT NULL,
	SEGUNDA_FEIRA VARCHAR(4) CHECK (segunda_feira in ('Sim', 'Não')), 
	TERCA_FEIRA VARCHAR(4) CHECK (segunda_feira in ('Sim', 'Não')),
	QUARTA_FEIRA VARCHAR(4) CHECK (segunda_feira in ('Sim', 'Não')),
	QUINTA_FEIRA VARCHAR(4) CHECK (segunda_feira in ('Sim', 'Não')),
	SEXTA_FEIRA VARCHAR(4) CHECK (segunda_feira in ('Sim', 'Não')),
    CONSTRAINT FK_DIAS_FREQUENTE FOREIGN KEY (CODIGO_BOLEIA) REFERENCES BOLEIA_FREQUENTE (CODIGO)
);

CREATE TABLE INSCRICAO(
    CODIGO NUMBER PRIMARY KEY,
	CODIGO_BOLEIA NUMBER,
	CODIGO_UTENTE NUMBER,
	DATA_INSCRICAO DATE,
    CONSTRAINT FK_CODIGO_UTENTE FOREIGN KEY (CODIGO_UTENTE) REFERENCES UTENTE (CODIGO), 
	CONSTRAINT FK_CODIGO_BOLEIA FOREIGN KEY (CODIGO_BOLEIA) REFERENCES BOLEIA (CODIGO)
);


